name: todolist
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  get: ^4.6.6
  iconify_flutter: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.14

  flutter_lints: ^5.0.0

flutter:
 
  uses-material-design: true
  
  assets:
    - assets/images/image1.png
    - assets/images/avatar.png

  
